- index.html
Created initial html setup to display code snippets when a button is pressed. Needs to be tested with node and database.
> Create html boilerplate

- index.html
Updated table to include sorting, filtering capabilities passed to middle tier via http get request with parameters passed.
> Added sorting, filtering capabilities to client side

- index.html
good to merge with dev, tested using other data, but now set up for use with `SNIP_SNIPPET`, so it will not work entirely until our database has been updated.
> added function to click rows and display SNIP_SNIPPET in modal

- createDB.sql
- server.js
Added it so the SQL file  creates a new user
sel_user
with its own password
updated the SQL query on server.js to incorporate stored procedures on the user input
> User and prepared procedures

- createDB.sql
Fixing mistake made when fixing merge conflicts
> Fix SQL Error

- createDB.sql
Hopefully this will work for everything else!
> Added Account table and Question table

- server.js
Added account creation on the server side
> R2.1 register json

- index.html
- server.js
> Dup email catching

- index.html
- server.js
Added stuff. Needs to be tested
> Login server side

- index.html
> Uncommented whoIsLoggedIn at 182

- server.js
Issue #72 
Issue #73 
Issue #74 
Issue #75
> Server side updates

- server.js
Fixed hashing so that answers are properly checked. Passwords can now be changed, but proper error responses need to be sent and displayed still
> Changed Hashing

- index.html
- server.js
- Created changePass Modal
- Integrated changePass modal with client and server side
- Error handling
- Found god
- Craved garlic knots
> Change pass client

- index.html
Re-fixing phantom bug (please comment code so we understand why things are happening)
> Re-commenting lines

- index.html
- server.js
> Commented code

- index.html
- server.js
> Capitalization fix

- index.html
> Encode decode

- index.html
Added URIencoding for language
> Added URI Enconding for the language

- index.html
- server.js
added ability for authenticated users to update and delete their own snippets
> Edit delete index and server

- index.html
Added Client-side question selection validation
> Registration questions
